# .goreleaser.yml
# Build customization
builds:
  - binary: fari-client
    main: ./client/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - binary: fari-server
    main: ./server/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  format_overrides:
      - goos: windows
        format: zip
  files:
    - .client.json
    - .server.json
    - supervisord.conf
    - whiteiplist.pac
