# .goreleaser.yml
# Build customization
builds:
  - binary: fari-client
    id: "client"
    main: ./client/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - binary: fari-server
    id: "server"
    main: ./client/main.go
    main: ./server/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  format_overrides:
      - goos: windows
        format: zip
  files:
    - .client.json
    - .server.json
    - fari-client.service
    - fari-server.service
    - supervisord.conf
    - whiteiplist.pac
    - start.sh
